### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by mcianfrocco** [thuem/THUNDER#11]
Dear THUNDER developers,

Do you have example test data to confirm correct installation / compiling of THUNDER? I am keen on using this and it would be very helpful to have pre-formatted data and .thu files so that I can confirm how to run the software before trying it on un-tested samples.

Thank you,
Mike

**Comment by Zarrathustra** [comment]
Thank you for your advice.

Currently, no. We have several internal pre-formatted test datasets, which may be upload to world wide web.

However, Accessing cloud drive from mainland China is a little bit thorny. We will try our best to upload them. If you have any advice on which cloud drive we should use, please tell us. Thank you in advance.

**Comment by mcianfrocco** [comment]
Hello - I just shared a shared Globus endpoint with your Tsinghua email address. If you download globus personal connect on your server, you can use the Globus web interface to move data from your server onto my server (if this is not blocked). 

Otherwise, I think you can upload small amounts to One Drive and then share this with me (or so I was told).

Alternatively - you could create an EMPIAR dataset that users could download in order to test THUNDER.

Thanks,
Mike

**Comment by Zarrathustra** [comment]
Thank you for your help.

We will try to upload. Once we accomplish uploading, we will get you informed.

Best regards.

Mingxu

**Comment by Zarrathustra** [comment]
We are uploading a dataset of AAV-AAVR complex, https://www.nature.com/articles/s41564-018-0356-7.

Due to limited bandwidth, it will take 10-20 hours. We will have you informed once accomplish uploading.

Sorry for the latency.

Best regards.

Mingxu

**Comment by mcianfrocco** [comment]
Thank you - I appreciate having the chance to run a standardized dataset.

If you do not mind, could you also include information on how long it took you run the job and what node/machine types? Just to make sure our compiled version is operating comparatively.

Thanks,
Mike

**Comment by Zarrathustra** [comment]
We have upload AAV-AAVR dataset as demo. Please check https://github.com/thuem/THUNDER-demo-datasets。

There is a demonstration running. The hardware and time consumption has been described in the README.md.

Sorry for the latency caused by the unstable Internet connection.

If you have any problem using THUNDER, please connect us. We will try our best to provide you help.

Moreover, you may have noticed that THUNDER has updated to version 1.4.12. The overall procedure of data analysis remains the same, however, there is some difference. We are working providing a renewed and redesigned manual here https://thuem.github.io/THUNDER/. As you may see, it is only half done. We are working on it and hope to accomplished it soon.

Best regards,
Mingxu

**Comment by Zarrathustra** [comment]
Dear Mike,

We have pushed the information on https://github.com/thuem/THUNDER-demo-datasets. We are using SLURM job management system. If you need more information about this system, for example, network, we can also provide you help.

Best wishes,

Mingxu

**Comment by Zarrathustra** [comment]
Information pushed on https://github.com/thuem/THUNDER-demo-datasets.

Close issue.
